// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: version.sql

package db

import (
	"context"
)

const getVersion = `-- name: GetVersion :one
SELECT version_number
FROM db_version
LIMIT 1
`

func (q *Queries) GetVersion(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, getVersion)
	var version_number int32
	err := row.Scan(&version_number)
	return version_number, err
}
