// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: proto/gallery.proto

package gallery

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PhotoFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PhotoFilter) Reset() {
	*x = PhotoFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gallery_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhotoFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhotoFilter) ProtoMessage() {}

func (x *PhotoFilter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhotoFilter.ProtoReflect.Descriptor instead.
func (*PhotoFilter) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{0}
}

type Photo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash         string `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Path         string `protobuf:"bytes,2,opt,name=Path,proto3" json:"Path,omitempty"`
	DateTime     string `protobuf:"bytes,3,opt,name=DateTime,proto3" json:"DateTime,omitempty"`
	Iso          int32  `protobuf:"varint,4,opt,name=Iso,proto3" json:"Iso,omitempty"`
	ExposureTime string `protobuf:"bytes,5,opt,name=ExposureTime,proto3" json:"ExposureTime,omitempty"`
	XDimension   int32  `protobuf:"varint,6,opt,name=XDimension,proto3" json:"XDimension,omitempty"`
	YDimension   int32  `protobuf:"varint,7,opt,name=YDimension,proto3" json:"YDimension,omitempty"`
	Model        string `protobuf:"bytes,8,opt,name=Model,proto3" json:"Model,omitempty"`
	FocalLength  string `protobuf:"bytes,9,opt,name=FocalLength,proto3" json:"FocalLength,omitempty"`
}

func (x *Photo) Reset() {
	*x = Photo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gallery_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Photo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Photo) ProtoMessage() {}

func (x *Photo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Photo.ProtoReflect.Descriptor instead.
func (*Photo) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{1}
}

func (x *Photo) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Photo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Photo) GetDateTime() string {
	if x != nil {
		return x.DateTime
	}
	return ""
}

func (x *Photo) GetIso() int32 {
	if x != nil {
		return x.Iso
	}
	return 0
}

func (x *Photo) GetExposureTime() string {
	if x != nil {
		return x.ExposureTime
	}
	return ""
}

func (x *Photo) GetXDimension() int32 {
	if x != nil {
		return x.XDimension
	}
	return 0
}

func (x *Photo) GetYDimension() int32 {
	if x != nil {
		return x.YDimension
	}
	return 0
}

func (x *Photo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Photo) GetFocalLength() string {
	if x != nil {
		return x.FocalLength
	}
	return ""
}

var File_proto_gallery_proto protoreflect.FileDescriptor

var file_proto_gallery_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x67, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x79, 0x22, 0x0d,
	0x0a, 0x0b, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0xf9, 0x01,
	0x0a, 0x05, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x61, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x50,
	0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50, 0x61, 0x74, 0x68, 0x12,
	0x1a, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x49,
	0x73, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x49, 0x73, 0x6f, 0x12, 0x22, 0x0a,
	0x0c, 0x45, 0x78, 0x70, 0x6f, 0x73, 0x75, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x45, 0x78, 0x70, 0x6f, 0x73, 0x75, 0x72, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x58, 0x44, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x58, 0x44, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x59, 0x44, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x59, 0x44, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x46, 0x6f, 0x63, 0x61, 0x6c,
	0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x46, 0x6f,
	0x63, 0x61, 0x6c, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x32, 0x40, 0x0a, 0x07, 0x47, 0x61, 0x6c,
	0x6c, 0x65, 0x72, 0x79, 0x12, 0x35, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x50, 0x68, 0x6f, 0x74, 0x6f,
	0x73, 0x12, 0x14, 0x2e, 0x67, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x79, 0x2e, 0x50, 0x68, 0x6f, 0x74,
	0x6f, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x1a, 0x0e, 0x2e, 0x67, 0x61, 0x6c, 0x6c, 0x65, 0x72,
	0x79, 0x2e, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x22, 0x00, 0x30, 0x01, 0x42, 0x37, 0x0a, 0x16, 0x66,
	0x72, 0x2e, 0x6d, 0x69, 0x63, 0x68, 0x61, 0x65, 0x6c, 0x63, 0x6f, 0x6c, 0x6c, 0x2e, 0x67, 0x61,
	0x6c, 0x6c, 0x65, 0x72, 0x79, 0x42, 0x0c, 0x47, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x79, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x0d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x6c,
	0x6c, 0x65, 0x72, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_gallery_proto_rawDescOnce sync.Once
	file_proto_gallery_proto_rawDescData = file_proto_gallery_proto_rawDesc
)

func file_proto_gallery_proto_rawDescGZIP() []byte {
	file_proto_gallery_proto_rawDescOnce.Do(func() {
		file_proto_gallery_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_gallery_proto_rawDescData)
	})
	return file_proto_gallery_proto_rawDescData
}

var file_proto_gallery_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_gallery_proto_goTypes = []interface{}{
	(*PhotoFilter)(nil), // 0: gallery.PhotoFilter
	(*Photo)(nil),       // 1: gallery.Photo
}
var file_proto_gallery_proto_depIdxs = []int32{
	0, // 0: gallery.Gallery.GetPhotos:input_type -> gallery.PhotoFilter
	1, // 1: gallery.Gallery.GetPhotos:output_type -> gallery.Photo
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_gallery_proto_init() }
func file_proto_gallery_proto_init() {
	if File_proto_gallery_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_gallery_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PhotoFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gallery_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Photo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_gallery_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gallery_proto_goTypes,
		DependencyIndexes: file_proto_gallery_proto_depIdxs,
		MessageInfos:      file_proto_gallery_proto_msgTypes,
	}.Build()
	File_proto_gallery_proto = out.File
	file_proto_gallery_proto_rawDesc = nil
	file_proto_gallery_proto_goTypes = nil
	file_proto_gallery_proto_depIdxs = nil
}
