// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package sqlc

import (
	"database/sql"
)

type Photo struct {
	Hash         string         `db:"hash"`
	Path         string         `db:"path"`
	DateTime     sql.NullString `db:"date_time"`
	Iso          sql.NullInt64  `db:"iso"`
	ExposureTime sql.NullString `db:"exposure_time"`
	XDimension   sql.NullInt64  `db:"x_dimension"`
	YDimension   sql.NullInt64  `db:"y_dimension"`
	Model        sql.NullString `db:"model"`
	FNumber      sql.NullString `db:"f_number"`
	Orientation  sql.NullInt64  `db:"orientation"`
}

type Thumbnail struct {
	Hash      string `db:"hash"`
	Height    int64  `db:"height"`
	Width     int64  `db:"width"`
	Thumbnail []byte `db:"thumbnail"`
}
