// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: photo.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countPhotoByHash = `-- name: CountPhotoByHash :one
SELECT COUNT(*)
FROM photos
WHERE hash = ?
`

func (q *Queries) CountPhotoByHash(ctx context.Context, db DBTX, hash string) (int64, error) {
	row := db.QueryRowContext(ctx, countPhotoByHash, hash)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPhotos = `-- name: CountPhotos :one
SELECT COUNT(*)
FROM photos
`

func (q *Queries) CountPhotos(ctx context.Context, db DBTX) (int64, error) {
	row := db.QueryRowContext(ctx, countPhotos)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrReplacePhoto = `-- name: CreateOrReplacePhoto :exec
REPLACE INTO photos (hash, path, date_time, iso, exposure_time, x_dimension, y_dimension, model, f_number)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateOrReplacePhotoParams struct {
	Hash         string         `db:"hash"`
	Path         string         `db:"path"`
	DateTime     sql.NullString `db:"date_time"`
	Iso          sql.NullInt64  `db:"iso"`
	ExposureTime sql.NullString `db:"exposure_time"`
	XDimension   sql.NullInt64  `db:"x_dimension"`
	YDimension   sql.NullInt64  `db:"y_dimension"`
	Model        sql.NullString `db:"model"`
	FNumber      sql.NullString `db:"f_number"`
}

func (q *Queries) CreateOrReplacePhoto(ctx context.Context, db DBTX, arg CreateOrReplacePhotoParams) error {
	_, err := db.ExecContext(ctx, createOrReplacePhoto,
		arg.Hash,
		arg.Path,
		arg.DateTime,
		arg.Iso,
		arg.ExposureTime,
		arg.XDimension,
		arg.YDimension,
		arg.Model,
		arg.FNumber,
	)
	return err
}

const deleteAllPhotoInPath = `-- name: DeleteAllPhotoInPath :exec
DELETE FROM photos
WHERE path LIKE ?
`

func (q *Queries) DeleteAllPhotoInPath(ctx context.Context, db DBTX, path string) error {
	_, err := db.ExecContext(ctx, deleteAllPhotoInPath, path)
	return err
}

const deleteAllPhotos = `-- name: DeleteAllPhotos :exec
DELETE FROM photos
WHERE 1
`

func (q *Queries) DeleteAllPhotos(ctx context.Context, db DBTX) error {
	_, err := db.ExecContext(ctx, deleteAllPhotos)
	return err
}

const deletePhotoByPath = `-- name: DeletePhotoByPath :exec
DELETE FROM photos
WHERE path = ?
`

func (q *Queries) DeletePhotoByPath(ctx context.Context, db DBTX, path string) error {
	_, err := db.ExecContext(ctx, deletePhotoByPath, path)
	return err
}

const getPhoto = `-- name: GetPhoto :one
SELECT hash, path, date_time, iso, exposure_time, x_dimension, y_dimension, model, f_number
FROM photos
WHERE hash = ?
`

type GetPhotoRow struct {
	Hash         string         `db:"hash"`
	Path         string         `db:"path"`
	DateTime     sql.NullString `db:"date_time"`
	Iso          sql.NullInt64  `db:"iso"`
	ExposureTime sql.NullString `db:"exposure_time"`
	XDimension   sql.NullInt64  `db:"x_dimension"`
	YDimension   sql.NullInt64  `db:"y_dimension"`
	Model        sql.NullString `db:"model"`
	FNumber      sql.NullString `db:"f_number"`
}

func (q *Queries) GetPhoto(ctx context.Context, db DBTX, hash string) (GetPhotoRow, error) {
	row := db.QueryRowContext(ctx, getPhoto, hash)
	var i GetPhotoRow
	err := row.Scan(
		&i.Hash,
		&i.Path,
		&i.DateTime,
		&i.Iso,
		&i.ExposureTime,
		&i.XDimension,
		&i.YDimension,
		&i.Model,
		&i.FNumber,
	)
	return i, err
}

const getThumbnail = `-- name: GetThumbnail :one
SELECT thumbnail
FROM photos
WHERE hash = ?
`

func (q *Queries) GetThumbnail(ctx context.Context, db DBTX, hash string) ([]byte, error) {
	row := db.QueryRowContext(ctx, getThumbnail, hash)
	var thumbnail []byte
	err := row.Scan(&thumbnail)
	return thumbnail, err
}

const list = `-- name: List :many
SELECT hash, path, date_time, iso, exposure_time, x_dimension, y_dimension, model, f_number
FROM photos
ORDER BY date_time DESC
LIMIT ? OFFSET ?
`

type ListParams struct {
	Limit  int64 `db:"limit"`
	Offset int64 `db:"offset"`
}

type ListRow struct {
	Hash         string         `db:"hash"`
	Path         string         `db:"path"`
	DateTime     sql.NullString `db:"date_time"`
	Iso          sql.NullInt64  `db:"iso"`
	ExposureTime sql.NullString `db:"exposure_time"`
	XDimension   sql.NullInt64  `db:"x_dimension"`
	YDimension   sql.NullInt64  `db:"y_dimension"`
	Model        sql.NullString `db:"model"`
	FNumber      sql.NullString `db:"f_number"`
}

func (q *Queries) List(ctx context.Context, db DBTX, arg ListParams) ([]ListRow, error) {
	rows, err := db.QueryContext(ctx, list, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRow{}
	for rows.Next() {
		var i ListRow
		if err := rows.Scan(
			&i.Hash,
			&i.Path,
			&i.DateTime,
			&i.Iso,
			&i.ExposureTime,
			&i.XDimension,
			&i.YDimension,
			&i.Model,
			&i.FNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateThumbnail = `-- name: UpdateThumbnail :exec
UPDATE photos
SET thumbnail = ?
WHERE hash = ?
`

type UpdateThumbnailParams struct {
	Thumbnail []byte `db:"thumbnail"`
	Hash      string `db:"hash"`
}

func (q *Queries) UpdateThumbnail(ctx context.Context, db DBTX, arg UpdateThumbnailParams) error {
	_, err := db.ExecContext(ctx, updateThumbnail, arg.Thumbnail, arg.Hash)
	return err
}
